sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 06170018
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t91tffCeSTraaUB75R9
    bucket-name: java-sky-take-out-223
    access-key-secret: F2gBr6ZpXYI1ZMJgZRIroNrXSjoWza
  redis:
    host: localhost
    port: 6379
    password: 06170018
    database: 0
